name: TooManyPerms
author: AlbeMiglio
website: github.com/AlbeMiglio/TooManyPerms/
version: 1.0.6
main: it.mycraft.toomanyperms.TooManyPerms
depend: [Vault]
commands:
  tmp:
    description: Main command
    aliases: [toomanyperms]
permissions:
  tmp.admin:
    default: op
    children:
      tmp.use: true
      tmp.reload: true
      tmp.check: true
      tmp.opcheck: true
      tmp.groupcheck: true
      tmp.version: true
  tmp.checks:
    default: op
    children:
      tmp.check: true
      tmp.opcheck: true
      tmp.groupcheck: true
  tmp.use: 
    default: false
  tmp.reload: 
    default: false
  tmp.check:
    default: false
  tmp.opcheck:
    default: false
  tmp.groupcheck: 
    default: false
  tmp.version:
    default: false